ZupIT/ritchie-server

LICENSE
NOTICE.md
README.md

change license

---

server/http/repository/repository_test.go
server/http/usagelogger/usagelogger_test.go
server/resources/security-constraints.yml

Change endpoint /metrics/use to /metrics/commands/use
Changing endpoint
Calling endpoint /metrics/commands/use in server using the method HTTP POST
Necessary change for the CLI to send commands to SERVER

Alter /metrics/use to /usage

---

README.md

fix doc url

---

.github/stale.yml

I added stale bot to the repo
By configuring the stale.yml file inside .github
See if the bot actually works after 60 days lul
Adding stale bot to ritchie

adding stale bot to repo

---

.circleci/config.yml
README.md
server/cmd/server/main.go
server/http/cliversion/cliversion.go
server/http/cliversion/cliversion_test.go
server/http/health/health.go
server/http/health/health_test.go
server/http/hello/hello.go
server/http/hello/hello_test.go
server/http/keycloak/keycloak.go
server/http/keycloak/keycloak_test.go
server/http/login/login.go
server/http/oauth/oauth.go
server/http/repository/repository.go
server/http/repository/repository_test.go
server/http/user/user.go
server/keycloak/keycloak_manager.go
server/keycloak/keycloak_manager_test.go
server/middleware/middleware.go
server/resources/security-constraints.yml
server/security/security.go
server/server.go
server/starter/starter.go
server/vault/vault_manager_test.go

Created endpoint for allowing set server to work
By adding a new package to the repo
See if the server returns 200 to when calling /
Adding the endpoint to allow the set server command to work properly

adding the / path so the set server works properly

---

Makefile

added build linux

---

.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md
README.md

- Updated Gitbook urls
- Updating Gitbook urls
- Clicking on Gitbook urls
- Update Gitbook urls

[FIX] updating gitbook urls

---

server/resources/security-constraints.yml

rit_user and rit_admin

---

.github/ritchie-bot-config.yml
CODEOWNERS

I updated slack token
[FEATURE] Update slack token

[FEATURE] Update slack token

---

.circleci/config.yml

Include HORUS Security Test in .circleci/config.yml
Include security_test in jobs and put in workflow to execute
Look the security_test and jobs steps in workflow configuration

[SECURITY] Include HORUS Security Test in .circleci/config.yml

---

.circleci/config.yml
go.mod

[FEATURE] Increase go version

---

server/sp/keycloak/keycloak_provider.go
server/sp/ldap/ldap_provider.go

Adjust TTL
Change keycloak provide and ldap provider
Local tests
Qa test
[FIX] fix ttl

[FIX] fix ttl

---

.circleci/config.yml
.circleci/scripts/credentials.sh
Makefile

- fix generate release
- run pipeline 
- fix generate release

[Fix] generate relese.

---

.circleci/scripts/registry.sh
.circleci/scripts/version.sh
Makefile

- Fix registry for beta
- Fix registry for beta
- run pipeline 
- Fix registry in step delivery for beta

fix registry for dockerhub

---

.circleci/config.yml

- Fix dockerhub delivery
- Fix dockerhub delivery in config.yml
- Run pipeline
- Fix dockerhub delivery in config.yml

Fix delivery dockerhub

---

.circleci/config.yml

- fix build container in config.yml
- fix build container in config.yml
- run pipeline
- fix build container in config.yml

fix in buildcontainer

---

.circleci/config.yml

- fix dockerhub
-  fix dockerhub
- run pipeline
- fix pipeline

fix dockerhub

---

Makefile

- Fix Makefile bug loop release
- Fix in makefile
- run pipeline in generate release
- Fix Makefile bug loop release

[Fix] Makefile bug release

---

.circleci/config.yml
Makefile

- Add delivery file in pipeline
- Add delivery file
- run pipeline
- Add delivery file in pipeline

add delivery file

---

.circleci/config.yml

- Improvements in pipeline
- Improvements in pipeline
- Run pipeline
- Improvements in pipeline

Fix in delivery file

---

CHANGELOG.md

Release 1.0.0-beta.7 merge with master

Release 1.0.0-beta.7 merge

---

.circleci/config.yml
.circleci/scripts/registry.sh
Makefile

- Remove registry ecr
- Remove registry ecr
- Not apply
- Remove registry ecr

Fix remove registry ecr

---

.github/PULL_REQUEST_TEMPLATE.md

Removed the question `How I did it` because the change files explain itself
Open a new PR after merge this branch
Simplify PR template

[ENHANCEMENT] simplify PR template
